import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import RoiDataProvider from "./Context/ROI_Data_Context";

export const metadata: Metadata = {
  title: "GreenSOl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RoiDataProvider>{children}</RoiDataProvider>
      </body>
    </html>
  );
}
